Fixing dependency name and error handling

diff --git a/android/build_android b/android/build_android
--- a/android/build_android
+++ b/android/build_android
@@ -22,7 +22,12 @@ function configure_env {
 	sudo apt-get -y install git-core gnupg flex bison gperf libsdl1.2-dev libesd0-dev libwxgtk2.8-dev \
 		squashfs-tools build-essential zip curl libncurses5-dev zlib1g-dev openjdk-6-jre openjdk-6-jdk \
 		pngcrush schedtool libxml2 libxml2-utils xsltproc g++-multilib lib32z1-dev lib32ncurses5-dev \
-		lib32readline-gplv2-dev gcc-multilib
+		lib32readline5-dev gcc-multilib
+	if [ $? -ne 0 ]
+	then
+		echo "Error installing dependencies!"
+		exit 1
+	fi
 
 	curl -s https://dl-ssl.google.com/dl/googlesource/git-repo/repo > $DIR/bin/repo
 
@@ -39,8 +44,6 @@ function configure_env {
 	header "Initializing CyanogenMod repository..."
 	cd $DIR/system
 	repo init -u git://github.com/CyanogenMod/android.git -b cm-$CM_VERSION
-
-	exit 0
 }
 
 header "Checking Linux distro..."
